name: Docker Image Sync

# 1. 定义触发方式：手动触发 (workflow_dispatch)
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: '源镜像名 (例如 elasticsearch)'
        required: true
        default: 'elasticsearch'
      image_tag:
        description: '镜像版本号 (例如 7.4.2)'
        required: true
        default: '7.4.2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 2. 登录阿里云容器镜像仓库
      - name: Login to Aliyun Registry
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_USERNAME }} --password-stdin ${{ secrets.ALIYUN_REGISTRY }}

      # 3. 拉取、打标签并推送镜像
      - name: Pull, Tag and Push
        run: |
          # 定义原始镜像和目标镜像变量
          SOURCE_IMAGE="${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}"
          
          # 【注意】请将下行中的“你的命名空间”替换为你阿里云上的真实命名空间
          TARGET_IMAGE="${{ secrets.ALIYUN_REGISTRY }}/clannadxi/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}"
          
          echo "正在从 Docker Hub 拉取: $SOURCE_IMAGE"
          docker pull $SOURCE_IMAGE
          
          echo "正在打标签为: $TARGET_IMAGE"
          docker tag $SOURCE_IMAGE $TARGET_IMAGE
          
          echo "正在推送到阿里云..."
          docker push $TARGET_IMAGE
          
          echo "=========================================="
          echo "同步成功！"
          echo "你可以在本地使用以下命令拉取："
          echo "docker pull $TARGET_IMAGE"
          echo "=========================================="
